# Generated by Django 4.1.7 on 2023-03-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='count_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.IntegerField()),
                ('text_reminders', models.BooleanField()),
                ('email_reminders', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='donation_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='donation_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='parishoner_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_state_name', models.CharField(max_length=100)),
                ('state_abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unnamed_donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('one_count', models.IntegerField()),
                ('two_count', models.IntegerField()),
                ('five_count', models.IntegerField()),
                ('ten_count', models.IntegerField()),
                ('twenty_count', models.IntegerField()),
                ('fifty_count', models.IntegerField()),
                ('hundred_count', models.IntegerField()),
                ('donation_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.donation_category')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.count')),
                ('donation_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.donation_note')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.payment_type')),
            ],
        ),
        migrations.CreateModel(
            name='parishoners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counting.family')),
            ],
        ),
        migrations.CreateModel(
            name='parishoner_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_data', models.CharField(max_length=100)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.contact_type')),
                ('parishoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.parishoners')),
            ],
        ),
        migrations.CreateModel(
            name='parishoner_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('parishoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.parishoners')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.parishoner_state')),
            ],
        ),
        migrations.CreateModel(
            name='named_donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('donation_detail_id', models.IntegerField(null=True)),
                ('donation_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.donation_category')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.count')),
                ('parishoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.parishoners')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.payment_type')),
            ],
        ),
        migrations.CreateModel(
            name='counter_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.counter')),
            ],
        ),
        migrations.AddField(
            model_name='count',
            name='count_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.count_type'),
        ),
    ]
