# Generated by Django 4.1.7 on 2023-07-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_donation_detail_donation_note_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_category_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counting.donation_category')),
            ],
        ),
        migrations.AddField(
            model_name='unnamed_donations',
            name='custom_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counting.donation_category_custom'),
        ),
    ]
