# Generated by Django 4.1.7 on 2023-07-14 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0003_donation_category_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_note',
            name='custom_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counting.donation_category_custom'),
        ),
    ]
